### GET Usuários
GET http://localhost:8080/api/v1/usuarios
Content-Type: application/json

### POST Usuários
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{   
    "nome": "Lucas",
    "email": "lucas@gmail.com",
    "telefone": "5555-5555",
    "senha": "1234",
    "tipo": "cliente"
}

### PUT Usuários
PUT  http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json

{   
  "nome": "LucasS",
  "email": "lucas@gmail.com",
  "telefone": "9999-5555",
  "senha": "1234",
  "tipo": "cliente"
}

### DELETE Usuários
DELETE  http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json


######## CRUD PETS ########

### GET Pets
GET http://localhost:8080/api/v1/pets
Content-Type: application/json

### POST Pets
POST http://localhost:8080/api/v1/pets
Content-Type: application/json

{
  "nome": "princesa",
  "raca": "Vira-lata",
  "idade": 4,
  "peso": 5.5
}

### PUT Pets
PUT http://localhost:8080/api/v1/pets/1
Content-Type: application/json

{
  "nome": "princesa",
  "raca": "Pitbull",
  "idade": 4,
  "peso": 5.5
}

### DELETE Pets
DELETE http://localhost:8080/api/v1/pets/1
Content-Type: application/json


######## CRUD RESERVAS ########

### GET Reservas
GET http://localhost:8080/api/v1/reservas
Content-Type: application/json

### POST Reservas
POST http://localhost:8080/api/v1/reservas
Content-Type: application/json

{
    "dataCheckIn": "2025-05-16",
    "dataCheckOut": "2025-05-20",
    "status": "Finalizado"
}

### PUT Reservas
PUT http://localhost:8080/api/v1/reservas/1
Content-Type: application/json

{
  "dataCheckIn": "2024-05-16",
    "dataCheckOut": "2024-10-20",
    "status": "Finalizado"
}

### DELETE Reservas
DELETE http://localhost:8080/api/v1/reservas/1
Content-Type: application/json


######## CRUD SERVICOS ########

### GET Servicos
GET http://localhost:8080/api/v1/servicos
Content-Type: application/json

### POST Servicos
POST http://localhost:8080/api/v1/servicos
Content-Type: application/json

{
    "nome": "Banho e Tosa",
    "descricao": "Serviço completo de banho e tosa para seu pet.",
    "valor": 120.00
}

### PUT Servicos
PUT http://localhost:8080/api/v1/servicos/1
Content-Type: application/json

{
    "nome": "Banho e Tosa",
    "descricao": "Serviço completo de banho e tosa para seu pet.",
    "valor": 200.00
}

### DELETE Servicos
DELETE http://localhost:8080/api/v1/servicos/1
Content-Type: application/json

